[2024-09-18T11:54:15.222+0100] {processor.py:186} INFO - Started process (PID=9492) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:54:15.222+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:54:15.223+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:54:15.223+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:54:15.247+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:54:15.246+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:54:15.247+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:54:15.247+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:54:15.247+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:54:15.296+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2024-09-18T11:54:49.437+0100] {processor.py:186} INFO - Started process (PID=9693) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:54:49.439+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:54:49.439+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:54:49.439+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:54:49.494+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:54:49.492+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:54:49.494+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:54:49.494+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:54:49.495+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:54:49.547+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-09-18T11:55:24.780+0100] {processor.py:186} INFO - Started process (PID=9873) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:55:24.780+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:55:24.781+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:55:24.780+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:55:24.800+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:55:24.800+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:55:24.800+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:55:24.800+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:55:24.800+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:55:24.838+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2024-09-18T11:55:56.446+0100] {processor.py:186} INFO - Started process (PID=10048) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:55:56.447+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:55:56.447+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:55:56.447+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:55:56.475+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:55:56.475+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:55:56.475+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:55:56.475+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:55:56.475+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:55:56.535+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-09-18T11:56:31.305+0100] {processor.py:186} INFO - Started process (PID=10179) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:56:31.305+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:56:31.306+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:56:31.306+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:56:31.322+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:56:31.321+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:56:31.322+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:56:31.322+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:56:31.322+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:56:31.357+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-09-18T11:57:03.319+0100] {processor.py:186} INFO - Started process (PID=10352) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:57:03.320+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:57:03.320+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:57:03.320+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:57:03.343+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:57:03.343+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:57:03.343+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:57:03.343+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:57:03.343+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:57:03.384+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-09-18T11:57:36.172+0100] {processor.py:186} INFO - Started process (PID=10518) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:57:36.172+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:57:36.172+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:57:36.172+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:57:36.191+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:57:36.191+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:57:36.192+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:57:36.192+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:57:36.192+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:57:36.235+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2024-09-18T11:58:10.877+0100] {processor.py:186} INFO - Started process (PID=10726) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:58:10.879+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:58:10.880+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:58:10.880+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:58:10.898+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:58:10.898+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:58:10.898+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:58:10.898+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:58:10.898+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:58:10.945+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2024-09-18T11:58:46.270+0100] {processor.py:186} INFO - Started process (PID=10896) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:58:46.271+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:58:46.272+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:58:46.272+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:58:46.292+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:58:46.291+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:58:46.292+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:58:46.292+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:58:46.292+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:58:46.326+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2024-09-18T11:59:20.289+0100] {processor.py:186} INFO - Started process (PID=11108) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:59:20.290+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:59:20.291+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:59:20.290+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:59:20.311+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:59:20.311+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:59:20.311+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:59:20.311+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:59:20.311+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:59:20.350+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2024-09-18T11:59:53.850+0100] {processor.py:186} INFO - Started process (PID=11282) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:59:53.852+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T11:59:53.853+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:59:53.853+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:59:53.872+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:59:53.871+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T11:59:53.872+0100] {logging_mixin.py:190} INFO - [2024-09-18T11:59:53.872+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T11:59:53.872+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T11:59:53.908+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2024-09-18T12:00:27.709+0100] {processor.py:186} INFO - Started process (PID=11491) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:00:27.712+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:00:27.712+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:00:27.712+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:00:27.731+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:00:27.730+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:00:27.731+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:00:27.731+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:00:27.731+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:00:27.764+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2024-09-18T12:01:00.410+0100] {processor.py:186} INFO - Started process (PID=11692) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:01:00.412+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:01:00.412+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:01:00.412+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:01:00.432+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:01:00.432+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:01:00.432+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:01:00.432+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:01:00.432+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:01:00.478+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-09-18T12:06:16.289+0100] {processor.py:186} INFO - Started process (PID=11919) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:06:16.305+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:06:16.305+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:06:16.305+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:06:16.322+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:06:16.322+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:06:16.322+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:06:16.322+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:06:16.322+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:06:16.355+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2024-09-18T12:06:49.149+0100] {processor.py:186} INFO - Started process (PID=12090) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:06:49.149+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:06:49.150+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:06:49.149+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:06:49.168+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:06:49.168+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:06:49.168+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:06:49.168+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:06:49.168+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:06:49.215+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-09-18T12:07:23.733+0100] {processor.py:186} INFO - Started process (PID=12260) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:07:23.734+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:07:23.734+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:07:23.734+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:07:23.754+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:07:23.754+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:07:23.754+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:07:23.754+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:07:23.754+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:07:23.789+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-09-18T12:08:08.383+0100] {processor.py:186} INFO - Started process (PID=12447) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:08:08.383+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:08:08.384+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:08:08.383+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:08:08.405+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:08:08.405+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:08:08.405+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:08:08.405+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:08:08.405+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:08:08.440+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2024-09-18T12:08:44.163+0100] {processor.py:186} INFO - Started process (PID=12652) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:08:44.163+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:08:44.164+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:08:44.163+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:08:44.181+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:08:44.180+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:08:44.181+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:08:44.181+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:08:44.181+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:08:44.214+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-09-18T12:09:17.321+0100] {processor.py:186} INFO - Started process (PID=12791) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:09:17.322+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:09:17.322+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:09:17.322+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:09:17.341+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:09:17.340+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:09:17.342+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:09:17.342+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:09:17.342+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:09:17.378+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-09-18T12:09:53.705+0100] {processor.py:186} INFO - Started process (PID=13004) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:09:53.706+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:09:53.706+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:09:53.706+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:09:53.727+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:09:53.727+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:09:53.727+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:09:53.727+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:09:53.727+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:09:53.774+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
[2024-09-18T12:10:26.438+0100] {processor.py:186} INFO - Started process (PID=13131) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:10:26.438+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:10:26.438+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:10:26.438+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:10:26.463+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:10:26.463+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:10:26.463+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:10:26.463+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:10:26.463+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:10:26.497+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-09-18T12:11:01.268+0100] {processor.py:186} INFO - Started process (PID=13306) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:11:01.269+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:11:01.269+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:11:01.269+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:11:01.284+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:11:01.284+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:11:01.284+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:11:01.284+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:11:01.284+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:11:01.320+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2024-09-18T12:11:35.220+0100] {processor.py:186} INFO - Started process (PID=13457) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:11:35.220+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:11:35.221+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:11:35.221+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:11:35.237+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:11:35.237+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:11:35.237+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:11:35.237+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:11:35.237+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:11:35.275+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2024-09-18T12:12:07.799+0100] {processor.py:186} INFO - Started process (PID=13613) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:12:07.800+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:12:07.800+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:12:07.800+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:12:07.821+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:12:07.820+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:12:07.821+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:12:07.821+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:12:07.821+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:12:07.886+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-09-18T12:12:41.359+0100] {processor.py:186} INFO - Started process (PID=13749) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:12:41.360+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:12:41.360+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:12:41.360+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:12:41.377+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:12:41.377+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:12:41.377+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:12:41.377+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:12:41.378+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:12:41.414+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.060 seconds
[2024-09-18T12:13:17.521+0100] {processor.py:186} INFO - Started process (PID=13960) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:13:17.521+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:13:17.522+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:13:17.522+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:13:17.541+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:13:17.541+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:13:17.541+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:13:17.541+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:13:17.541+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:13:17.582+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2024-09-18T12:13:51.361+0100] {processor.py:186} INFO - Started process (PID=14082) to work on /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:13:51.362+0100] {processor.py:914} INFO - Processing file /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-09-18T12:13:51.362+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:13:51.362+0100] {dagbag.py:587} INFO - Filling up the DagBag from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:13:51.380+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:13:51.380+0100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-09-18T12:13:51.380+0100] {logging_mixin.py:190} INFO - [2024-09-18T12:13:51.380+0100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-09-18T12:13:51.380+0100] {processor.py:927} WARNING - No viable dags retrieved from /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-09-18T12:13:51.432+0100] {processor.py:208} INFO - Processing /Users/ds2718/Documents/test_python_airflow/airflow/py_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
